/*
 *  RedBalls (not in the UrbanDictionary definintion!): 
 *  A clone of the popular Worms game, runnin on uChip Simple VGA Console
 *  a simple Cortex M0+ console with 32 kB of RAM!
 *
 *  Copyright 2019-2020 Nicola Wrachien (next-hack.com)
 *
 *  This file is part of next-hack's RedBalls.
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program  is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *	
 *  tl;dr 
 *  Do whatever you want, this program is free! Though we won't 
 *  reject donations https://next-hack.com/index.php/donate/ :) 
 *
 *
 * VGAspriteData.h: this file is (mostly) generated automatically by the uChip Game MapEditor
 */
#ifndef VGASPRITEDATA_H_
#define VGASPRITEDATA_H_
#include "usvc_kernel/vga.h"
#if GFX_MODE == TILE_MODE1 || GFX_MODE == TILE_MODE2
#include <stdint.h>
//
//
#include <stdint.h>
#define SPRITEDATA_NUMPIXELS 56451
#define FRAMEDATA_NUMFRAMES 914
#define ANIMDATA_NUMANIM 52
#define ENTITYDATA_NUMENTITIES 30
#define PLAYER 0
#define DYNAMITE 1
#define GRENADE 2
#define ROCKET 3
#define WEAPON_POINTER 4
#define WATER 5
#define EXPLOSION 6
#define CLOUD1 7
#define CLOUD2 8
#define CLOUD3 9
#define CLOUD4 10
#define DAMAGEMASK8 11
#define DAMAGEMASK16 12
#define DAMAGEMASK24 13
#define DAMAGEMASK32 14
#define DAMAGEMASK40 15
#define TEAMRED 16
#define TEAMBLUE 17
#define TEAMYELLOW 18
#define TEAMGREY 19
#define CURRENTUNIT 20
#define HEALTH 21
#define MEDIPACK 22
#define AMMO 23
#define BOMBLET 24
#define MINE 25
#define SMOKE16 26
#define AIRSTRIKE 27
#define BLOWTORCH_DAMAGEMASK 28
#define DRILL_DAMAGEMASK 29
#define PLAYER_WALK 0
#define PLAYER_BAZOOKA_SHOOT_UP 1
#define PLAYER_WALK_BAZOOKA 2
#define PLAYER_BAZOOKA_SHOOT_DOWN 3
#define PLAYER_BLOWTORCH_IGNITE_DOWN 4
#define PLAYER_DEATH 5
#define PLAYER_WALK_SHOTGUN 6
#define PLAYER_SHOTGUN_SHOOT_UP 7
#define PLAYER_BLOWTORCH_IGNITE_STRAIGHT 8
#define PLAYER_WALK_BLOWTORCH 9
#define PLAYER_DRILL_ANIM 10
#define PLAYER_BAZOOKA_SHOOT_STRAIGHT 11
#define PLAYER_BAZOOKA_AIM 12
#define PLAYER_BLOWTORCH_IGNITE_UP 13
#define PLAYER_SHOTGUN_SHOOT_STRAIGHT 14
#define PLAYER_TELEPORT 15
#define PLAYER_SHOTGUN_SHOOT_DOWN 16
#define PLAYER_THROW_GRENADE 17
#define PLAYER_FLY_AWAY 18
#define DYNAMITE_BURNING 0
#define GRENADE_FLYING 0
#define ROCKET_FLYING 0
#define WEAPON_POINTER_AIM 0
#define WATER_WAVES 0
#define EXPLOSION_EXPLOSION 0
#define CLOUD1_CLOUD 0
#define CLOUD2_CLOUD 0
#define CLOUD3_CLOUD 0
#define CLOUD4_CLOUD 0
#define DAMAGEMASK8_DAMAGEMASK8 0
#define DAMAGEMASK16_DAMAGEMASK16 0
#define DAMAGEMASK24_DAMAGEMASK24 0
#define DAMAGEMASK32_DAMAGEMASK32 0
#define DAMAGEMASK40_DAMAGEMASK40 0
#define TEAMRED_INDICATOR 0
#define TEAMBLUE_INDICATOR 0
#define TEAMYELLOW_INDICATOR 0
#define TEAMGREY_INDICATOR 0
#define CURRENTUNIT_INDICATOR 0
#define HEALTH_VALUE 0
#define MEDIPACK_BONUS 0
#define AMMO_BONUS 0
#define BOMBLET_ROTATING 0
#define MINE_ROTATING 0
#define SMOKE16_SMOKE16 0
#define AIRSTRIKE_ARROW 0
#define BLOWTORCH_DAMAGEMASK_UP_RIGHT 0
#define BLOWTORCH_DAMAGEMASK_DOWN_RIGHT 1
#define BLOWTORCH_DAMAGEMASK_DOWN_LEFT 2
#define BLOWTORCH_DAMAGEMASK_UP_LEFT 3
#define BLOWTORCH_DAMAGEMASK_STRAIGHT 4
#define DRILL_DAMAGEMASK_DOWN 0
#define PLAYER_WALK_FRAMEINDEX 0x0000
#define PLAYER_BAZOOKA_SHOOT_UP_FRAMEINDEX 0x000C
#define PLAYER_WALK_BAZOOKA_FRAMEINDEX 0x0012
#define PLAYER_BAZOOKA_SHOOT_DOWN_FRAMEINDEX 0x001E
#define PLAYER_BLOWTORCH_IGNITE_DOWN_FRAMEINDEX 0x0024
#define PLAYER_DEATH_FRAMEINDEX 0x003C
#define PLAYER_WALK_SHOTGUN_FRAMEINDEX 0x0049
#define PLAYER_SHOTGUN_SHOOT_UP_FRAMEINDEX 0x0055
#define PLAYER_BLOWTORCH_IGNITE_STRAIGHT_FRAMEINDEX 0x0065
#define PLAYER_WALK_BLOWTORCH_FRAMEINDEX 0x007D
#define PLAYER_DRILL_ANIM_FRAMEINDEX 0x0089
#define PLAYER_BAZOOKA_SHOOT_STRAIGHT_FRAMEINDEX 0x0099
#define PLAYER_BAZOOKA_AIM_FRAMEINDEX 0x009F
#define PLAYER_BLOWTORCH_IGNITE_UP_FRAMEINDEX 0x00A1
#define PLAYER_SHOTGUN_SHOOT_STRAIGHT_FRAMEINDEX 0x00B9
#define PLAYER_TELEPORT_FRAMEINDEX 0x00C9
#define PLAYER_SHOTGUN_SHOOT_DOWN_FRAMEINDEX 0x00DC
#define PLAYER_THROW_GRENADE_FRAMEINDEX 0x00EC
#define PLAYER_FLY_AWAY_FRAMEINDEX 0x00F5
#define DYNAMITE_BURNING_FRAMEINDEX 0x0105
#define GRENADE_FLYING_FRAMEINDEX 0x0110
#define ROCKET_FLYING_FRAMEINDEX 0x0112
#define WEAPON_POINTER_AIM_FRAMEINDEX 0x0117
#define WATER_WAVES_FRAMEINDEX 0x0118
#define EXPLOSION_EXPLOSION_FRAMEINDEX 0x011F
#define CLOUD1_CLOUD_FRAMEINDEX 0x012B
#define CLOUD2_CLOUD_FRAMEINDEX 0x012C
#define CLOUD3_CLOUD_FRAMEINDEX 0x012D
#define CLOUD4_CLOUD_FRAMEINDEX 0x012E
#define DAMAGEMASK8_DAMAGEMASK8_FRAMEINDEX 0x012F
#define DAMAGEMASK16_DAMAGEMASK16_FRAMEINDEX 0x0130
#define DAMAGEMASK24_DAMAGEMASK24_FRAMEINDEX 0x0131
#define DAMAGEMASK32_DAMAGEMASK32_FRAMEINDEX 0x0132
#define DAMAGEMASK40_DAMAGEMASK40_FRAMEINDEX 0x0133
#define TEAMRED_INDICATOR_FRAMEINDEX 0x0134
#define TEAMBLUE_INDICATOR_FRAMEINDEX 0x0138
#define TEAMYELLOW_INDICATOR_FRAMEINDEX 0x013C
#define TEAMGREY_INDICATOR_FRAMEINDEX 0x0140
#define CURRENTUNIT_INDICATOR_FRAMEINDEX 0x0144
#define HEALTH_VALUE_FRAMEINDEX 0x0145
#define MEDIPACK_BONUS_FRAMEINDEX 0x01AA
#define AMMO_BONUS_FRAMEINDEX 0x01AB
#define BOMBLET_ROTATING_FRAMEINDEX 0x01AC
#define MINE_ROTATING_FRAMEINDEX 0x01AE
#define SMOKE16_SMOKE16_FRAMEINDEX 0x01B6
#define AIRSTRIKE_ARROW_FRAMEINDEX 0x01C1
#define BLOWTORCH_DAMAGEMASK_UP_RIGHT_FRAMEINDEX 0x01C3
#define BLOWTORCH_DAMAGEMASK_DOWN_RIGHT_FRAMEINDEX 0x01C4
#define BLOWTORCH_DAMAGEMASK_DOWN_LEFT_FRAMEINDEX 0x01C5
#define BLOWTORCH_DAMAGEMASK_UP_LEFT_FRAMEINDEX 0x01C6
#define BLOWTORCH_DAMAGEMASK_STRAIGHT_FRAMEINDEX 0x01C7
#define DRILL_DAMAGEMASK_DOWN_FRAMEINDEX 0x01C8
#define PLAYER_WALK_NUMFRAMES 0x000C
#define PLAYER_BAZOOKA_SHOOT_UP_NUMFRAMES 0x0006
#define PLAYER_WALK_BAZOOKA_NUMFRAMES 0x000C
#define PLAYER_BAZOOKA_SHOOT_DOWN_NUMFRAMES 0x0006
#define PLAYER_BLOWTORCH_IGNITE_DOWN_NUMFRAMES 0x0018
#define PLAYER_DEATH_NUMFRAMES 0x000D
#define PLAYER_WALK_SHOTGUN_NUMFRAMES 0x000C
#define PLAYER_SHOTGUN_SHOOT_UP_NUMFRAMES 0x0010
#define PLAYER_BLOWTORCH_IGNITE_STRAIGHT_NUMFRAMES 0x0018
#define PLAYER_WALK_BLOWTORCH_NUMFRAMES 0x000C
#define PLAYER_DRILL_ANIM_NUMFRAMES 0x0010
#define PLAYER_BAZOOKA_SHOOT_STRAIGHT_NUMFRAMES 0x0006
#define PLAYER_BAZOOKA_AIM_NUMFRAMES 0x0002
#define PLAYER_BLOWTORCH_IGNITE_UP_NUMFRAMES 0x0018
#define PLAYER_SHOTGUN_SHOOT_STRAIGHT_NUMFRAMES 0x0010
#define PLAYER_TELEPORT_NUMFRAMES 0x0013
#define PLAYER_SHOTGUN_SHOOT_DOWN_NUMFRAMES 0x0010
#define PLAYER_THROW_GRENADE_NUMFRAMES 0x0009
#define PLAYER_FLY_AWAY_NUMFRAMES 0x0010
#define DYNAMITE_BURNING_NUMFRAMES 0x000B
#define GRENADE_FLYING_NUMFRAMES 0x0002
#define ROCKET_FLYING_NUMFRAMES 0x0005
#define WEAPON_POINTER_AIM_NUMFRAMES 0x0001
#define WATER_WAVES_NUMFRAMES 0x0007
#define EXPLOSION_EXPLOSION_NUMFRAMES 0x000C
#define CLOUD1_CLOUD_NUMFRAMES 0x0001
#define CLOUD2_CLOUD_NUMFRAMES 0x0001
#define CLOUD3_CLOUD_NUMFRAMES 0x0001
#define CLOUD4_CLOUD_NUMFRAMES 0x0001
#define DAMAGEMASK8_DAMAGEMASK8_NUMFRAMES 0x0001
#define DAMAGEMASK16_DAMAGEMASK16_NUMFRAMES 0x0001
#define DAMAGEMASK24_DAMAGEMASK24_NUMFRAMES 0x0001
#define DAMAGEMASK32_DAMAGEMASK32_NUMFRAMES 0x0001
#define DAMAGEMASK40_DAMAGEMASK40_NUMFRAMES 0x0001
#define TEAMRED_INDICATOR_NUMFRAMES 0x0004
#define TEAMBLUE_INDICATOR_NUMFRAMES 0x0004
#define TEAMYELLOW_INDICATOR_NUMFRAMES 0x0004
#define TEAMGREY_INDICATOR_NUMFRAMES 0x0004
#define CURRENTUNIT_INDICATOR_NUMFRAMES 0x0001
#define HEALTH_VALUE_NUMFRAMES 0x0065
#define MEDIPACK_BONUS_NUMFRAMES 0x0001
#define AMMO_BONUS_NUMFRAMES 0x0001
#define BOMBLET_ROTATING_NUMFRAMES 0x0002
#define MINE_ROTATING_NUMFRAMES 0x0008
#define SMOKE16_SMOKE16_NUMFRAMES 0x000B
#define AIRSTRIKE_ARROW_NUMFRAMES 0x0002
#define BLOWTORCH_DAMAGEMASK_UP_RIGHT_NUMFRAMES 0x0001
#define BLOWTORCH_DAMAGEMASK_DOWN_RIGHT_NUMFRAMES 0x0001
#define BLOWTORCH_DAMAGEMASK_DOWN_LEFT_NUMFRAMES 0x0001
#define BLOWTORCH_DAMAGEMASK_UP_LEFT_NUMFRAMES 0x0001
#define BLOWTORCH_DAMAGEMASK_STRAIGHT_NUMFRAMES 0x0001
#define DRILL_DAMAGEMASK_DOWN_NUMFRAMES 0x0001
typedef struct
{
	uint16_t frameIndex;  //index to the first frame data
	uint8_t numFrames;  //number of frames
} anim_t;
extern const uint8_t spriteData[SPRITEDATA_NUMPIXELS];
extern const frame_t frameData[FRAMEDATA_NUMFRAMES];
extern const anim_t animData[ANIMDATA_NUMANIM];
extern const anim_t* entityData[ENTITYDATA_NUMENTITIES];
extern const uint16_t entityAnimStartIndex[ENTITYDATA_NUMENTITIES]; // this is redundant but by using this, the compiler will save a lot of RAM
#endif




#endif /* VGASPRITEDATA_H_ */